### PR TITLE
Update json major version

### PR DESCRIPTION
**Pull request by urigolani**

### CODE REVIEW

**Comment by urigolani** [comment]
@danhstevens could you take a look?

**Comment by danhstevens** [comment]
Hey thanks for the PR (and the nudge) @urigolani! I'll have this looked over tomorrow.

**Comment by rathboma** [comment]
This does end support for ruby < 2.0, but given that 1.9 is no longer supported I think this is fine. Will merge

**Comment by rathboma** [comment]
Hey @urigolani just took another look at this and seems like we have a bunch of ruby users still on 1.8 and 1.9, so going to reject.

Are you having compatibility issues?

**Comment by urigolani** [comment]
@rathboma This problem with this is that kickbox is blocking us from enjoying the security updates on json by locking the major version.
What if I make it less obtrusive by doing
```gem.add_dependency "json", ">= 1.8"```

**Comment by rathboma** [comment]
I'm down with that.

**Pull request closed without merging**
